name: reff_web
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reff_shared:
    path: ../reff_shared
  hooks_riverpod: ^0.5.1
  flutter_hooks: ^0.13.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  state_notifier: ^0.5.0
  cloud_firestore: ^0.13.7
  logging: ^0.11.4
  get_it: ^4.0.4
  intl: ^0.16.1
  google_fonts: ^1.1.0
  freezed_annotation: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.3.0
  freezed: ^0.11.5

flutter:
  uses-material-design: true
