name: reff_web
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reff_shared:
    path: ../reff_shared
  state_notifier: ^0.6.0
  hooks_riverpod: ^0.9.1
  flutter_hooks: ^0.13.2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  logging: ^0.11.4
  get_it: ^4.0.4
  intl: ^0.16.1
  freezed_annotation: ^0.11.0+1
  searchable_dropdown: ^1.1.3
  sortedmap: ^0.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.1
  json_serializable: ^3.4.1
  freezed: ^0.11.6
  effective_dart: ^1.2.4


flutter:
  uses-material-design: true
